project:
  type: website
  output-dir: docs

website:
  title: "Home"
  site-url: https://simonm3.github.io/qblog
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com

  google-analytics: 
      tracking-id: "G-2VEP128SFL"

  margin-header: subscribe.html

format:
  html:
    theme: cosmo
    css: styles.css

comments:
  giscus:
    repo: simonm3/qblog